{% set name = "tsase" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://theory.cm.utexas.edu/code/{{ name }}.tgz
  sha256: a1a4f35fc161be504a37ce1467609940dd1eac7424a1dee89e27edb36875e4fc

build:
  number: 7
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build: 
    - make 
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - ase <3.23
    - numpy

test:
  imports:
    - tsase
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://theory.cm.utexas.edu/tsase/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'The TSASE library contains python code which depends on ASE to tackle transition state calculations.'
  description: |
    Our TSASE (pronounced “sassy”) library is an extension to ASE for
    transistion state calculations. If you are looking for our Solid
    State NEB or Kinetic Database code, you are in the right place.
  doc_url: https://theory.cm.utexas.edu/tsase/
  dev_url: https://theory.cm.utexas.edu/tsase/

extra:
  recipe-maintainers:
    - jan-janssen
